### ISSUE TITLE
Where is the data of the graph ?

### ISSUE THREAD

**Issue by bwhideaki** [palle-k/Graphite#2]
Hi !
I'm hideaki and this project is suprising !!
I want to know how to define the graph or how to load the data of graph.

**Comment by palle-k** [comment]
Hello hideaki!

You can see the type definition for the graph struct in [Graph.swift](https://github.com/palle-k/Graphite/blob/master/Sources/Graph.swift). 

To create a graph, you simply provide a list of integer node IDs and edges:

```swift
let graph = Graph(
    nodes: [1, 2, 3, 4, 5],
    edges: [
        Graph.Edge(nodes: [1, 2], weight: 1),
        Graph.Edge(nodes: [2, 3], weight: 1),
        Graph.Edge(nodes: [3, 4], weight: 1),
        Graph.Edge(nodes: [4, 5], weight: 1),
        Graph.Edge(nodes: [5, 1], weight: 1)
    ]
)
```

If you want to see more code examples, make sure to check out the demo project, that you can find in the [GraphiteDemo directory](https://github.com/palle-k/Graphite/tree/master/GraphiteDemo) in this repository. Most of the relevant code should be in the ViewController.swift file.

I hope I could help you.
Let me know if you have further questions.
